Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120
